name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  # Run unit test before pushing the code
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  #Perform linting using KtLint
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install ktlint
      - name: Run KtLint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report-in-checkstyle-format.xml
      - uses: yutailang0119/action-ktlint@v1.0.0
        with:
          xml_path: build/ktlint-report-in-checkstyle-format.xml

  #Generate an unsigned apk and uploads it as an artifact
  build:
    name: Generate Unsigned APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Build unsigned apk
      - name: Build Unsigned APK
        run: bash ./gradlew :app:assembleDebug

        #Upload unsigned apk as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Notflix
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
